// Type declarations for lucide-react deep imports (tree-shake friendly, default exports)
type LucideIconProps = { size?: number; style?: React.CSSProperties; className?: string };
declare module "lucide-react/dist/esm/icons/layout-dashboard" { const LayoutDashboard: React.FC<LucideIconProps>; export default LayoutDashboard; }
declare module "lucide-react/dist/esm/icons/car" { const Car: React.FC<LucideIconProps>; export default Car; }
declare module "lucide-react/dist/esm/icons/receipt" { const Receipt: React.FC<LucideIconProps>; export default Receipt; }
declare module "lucide-react/dist/esm/icons/shopping-cart" { const ShoppingCart: React.FC<LucideIconProps>; export default ShoppingCart; }
declare module "lucide-react/dist/esm/icons/landmark" { const Landmark: React.FC<LucideIconProps>; export default Landmark; }
declare module "lucide-react/dist/esm/icons/truck" { const Truck: React.FC<LucideIconProps>; export default Truck; }
declare module "lucide-react/dist/esm/icons/users" { const Users: React.FC<LucideIconProps>; export default Users; }
declare module "lucide-react/dist/esm/icons/user-check" { const UserCheck: React.FC<LucideIconProps>; export default UserCheck; }
declare module "lucide-react/dist/esm/icons/clipboard-check" { const ClipboardCheck: React.FC<LucideIconProps>; export default ClipboardCheck; }
declare module "lucide-react/dist/esm/icons/building-2" { const Building2: React.FC<LucideIconProps>; export default Building2; }
declare module "lucide-react/dist/esm/icons/user" { const User: React.FC<LucideIconProps>; export default User; }
declare module "lucide-react/dist/esm/icons/log-out" { const LogOut: React.FC<LucideIconProps>; export default LogOut; }
declare module "lucide-react/dist/esm/icons/search" { const Search: React.FC<LucideIconProps>; export default Search; }
declare module "lucide-react/dist/esm/icons/menu" { const Menu: React.FC<LucideIconProps>; export default Menu; }
declare module "lucide-react/dist/esm/icons/x" { const X: React.FC<LucideIconProps>; export default X; }
declare module "lucide-react/dist/esm/icons/trending-up" { const TrendingUp: React.FC<LucideIconProps>; export default TrendingUp; }
declare module "lucide-react/dist/esm/icons/alert-triangle" { const AlertTriangle: React.FC<LucideIconProps>; export default AlertTriangle; }
declare module "lucide-react/dist/esm/icons/phone" { const Phone: React.FC<LucideIconProps>; export default Phone; }
